version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db 

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379" 

  discountdb:
    container_name: discountdb
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a*wvmV7Q
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgress_data:/var/lib/postgressql/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
      #- "443"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"
      #- "443"  

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - "DatabaseSettings:ConnectionString=Server=host.docker.internal;Database=DiscountDb;Port=5432;User Id=postgres;Password=a*wvmV7Q;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"
      #- "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
